### ISSUE TITLE
Bug: Support for Linux

### ISSUE THREAD

**Issue by nikeokoronkwo** [prouesse/seagort#1]
## Overview
This bug concerns users making use of Seagort on Linux. 
Apparently it seems that the Dart `ffi` dynamic library lookup cannot find the symbols defined by the generated shared library used for Seagort

## Steps to Reproduce
This was tested on Ubuntu via Github Actions, and Separately on Docker.
1. With a fresh clone of the repository, build the engine at `utils/engine` using `cargo`
2. Copy the generated .so file to the `bridge/linux` folder.
3. Run the example code

## Expected Result
The example exits with exit code 0.
## Current Result
```log
Unhandled exception:
Invalid argument(s): Couldn't resolve native function 'compile_js' in 'package:seagort/src/native/library.dart' : No asset with id 'package:seagort/src/native/library.dart' found. No available native assets. Attempted to fallback to process lookup. dart: undefined symbol: compile_js.

#0      Native._ffi_resolver.#ffiClosure0 (dart:ffi-patch/ffi_patch.dart)
#1      Native._ffi_resolver_function (dart:ffi-patch/ffi_patch.dart:1386:20)
#2      compile_js (package:seagort/src/native/library.dart)
#3      _compileJS (package:seagort/src/lib/compile.dart:9:18)
#4      compileJavaSript (package:seagort/src/lib/compile.dart:17:39)
#5      compileJS (package:seagort/src/js.dart:4:32)
#6      main (file:///home/runner/work/seagort/seagort/example/main.dart:4:3)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

This problem is tracked on dart-lang/native#1087

**Comment by nikeokoronkwo** [comment]
Issue resolved. See dartlang-native-1087 branch for more info
